__OES_ORD_BASE_INFO_PKT = {
    "clSeqNo": "int32",
    "mktId": "uint8",
    "ordType": "uint8",
    "bsType": "uint8",
    "__ORD_BASE_INFO_filler": "uint8",
    "invAcctId": "string",
    "securityId": "string",
    "ordQty": "int32",
    "ordPrice": "int32",
    "origClOrdId": "int64",
}
__OES_ORD_CANCEL_BASE_INFO_PKT = {
    "clSeqNo": "int32",
    "mktId": "uint8",
    "__ORD_CANCEL_BASE_INFO_filler1": "uint8",
    "invAcctId": "string",
    "securityId": "string",
    "origClSeqNo": "int32",
    "origClEnvId": "int8",
    "__ORD_CANCEL_BASE_INFO_filler2": "uint8",
    "origClOrdId": "int64",
}
__OES_ORD_REQ_LATENCY_FIELDS_IMPL = {
    "__ordReqOrigSendTime": "STimespec32T",
}
__OES_ORD_CNFM_LATENCY_FIELDS_IMPL = {
    "__ordReqOrigRecvTime": "STimespec32T",
    "__ordReqCollectedTime": "STimespec32T",
    "__ordReqActualDealTime": "STimespec32T",
    "__ordReqProcessedTime": "STimespec32T",
    "__ordCnfmOrigRecvTime": "STimespec32T",
    "__ordCnfmCollectedTime": "STimespec32T",
    "__ordCnfmActualDealTime": "STimespec32T",
    "__ordCnfmProcessedTime": "STimespec32T",
    "__ordDeclareTime": "STimespec32T",
    "__ordDeclareDoneTime": "STimespec32T",
    "__pushingTime": "STimespec32T",
}
__OES_ORD_CNFM_BASE_INFO_PKT = {
    "__OES_ORD_BASE_INFO_PKT": "dict",
    "__OES_ORD_REQ_LATENCY_FIELDS": "dict",
    "clOrdId": "int64",
    "clientId": "int16",
    "clEnvId": "int8",
    "origClEnvId": "int8",
    "origClSeqNo": "int32",
    "ordDate": "int32",
    "ordTime": "int32",
    "ordCnfmTime": "int32",
    "ordStatus": "uint8",
    "ordCnfmSts": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "__platformId": "uint8",
    "__tgwGrpNo": "uint8",
    "__tgwPartitionNo": "uint8",
    "productType": "uint8",
    "exchOrdId": "string",
    "__declareFlag": "uint8",
    "__repeatFlag": "uint8",
    "ownerType": "uint8",
    "frzAmt": "int64",
    "frzInterest": "int64",
    "frzFee": "int64",
    "cumAmt": "int64",
    "cumInterest": "int64",
    "cumFee": "int64",
    "cumQty": "int32",
    "canceledQty": "int32",
    "ordRejReason": "int32",
    "exchErrCode": "int32",
    "pbuId": "int32",
    "branchId": "int32",
    "__rowNum": "int32",
    "__recNum": "uint32",
    "__OES_ORD_CNFM_LATENCY_FIELDS": "dict",
}
__OES_TRD_BASE_INFO_PKT = {
    "exchTrdNum": "int64",
    "mktId": "uint8",
    "trdSide": "uint8",
    "__platformId": "uint8",
    "__trdCnfmType": "uint8",
    "__etfTrdCnfmSeq": "uint32",
    "invAcctId": "string",
    "securityId": "string",
    "trdDate": "int32",
    "trdTime": "int32",
    "trdQty": "int32",
    "trdPrice": "int32",
    "trdAmt": "int64",
    "clOrdId": "int64",
    "cumQty": "int32",
    "__rowNum": "int32",
    "__tgwGrpNo": "uint8",
    "__isTrsfInCashAvailable": "uint8",
    "__tgwPartitionNo": "uint8",
    "productType": "uint8",
    "origOrdQty": "int32",
    "pbuId": "int32",
    "branchId": "int32",
}
__OES_TRD_BASE_LATENCY_FIELDS = {
    "__trdCnfmOrigRecvTime": "STimespec32T",
    "__trdCnfmCollectedTime": "STimespec32T",
    "__trdCnfmActualDealTime": "STimespec32T",
    "__trdCnfmProcessedTime": "STimespec32T",
    "__pushingTime": "STimespec32T",
}
__OES_TRD_CNFM_BASE_INFO_PKT = {
    "__OES_TRD_BASE_INFO_PKT": "dict",
    "clSeqNo": "int32",
    "clientId": "int16",
    "clEnvId": "int8",
    "subSecurityType": "uint8",
    "ordStatus": "uint8",
    "ordType": "uint8",
    "ordBuySellType": "uint8",
    "securityType": "uint8",
    "origOrdPrice": "int32",
    "cumAmt": "int64",
    "cumInterest": "int64",
    "cumFee": "int64",
    "__OES_TRD_CNFM_LATENCY_FIELDS": "dict",
}
__OES_LOT_WINNING_BASE_INFO_PKT = {
    "invAcctId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "lotType": "uint8",
    "rejReason": "uint8",
    "__LOT_WINNING_BASE_INFO_filler": "int8",
    "lotDate": "int32",
    "securityName": "string",
    "assignNum": "int64",
    "lotQty": "int32",
    "lotPrice": "int32",
    "lotAmt": "int64",
}
__OES_FUND_TRSF_BASE_INFO_PKT = {
    "clSeqNo": "int32",
    "direct": "uint8",
    "isAllotOnly": "uint8",
    "__FUND_TRSF_BASE_filler": "uint8",
    "cashAcctId": "string",
    "trdPasswd": "string",
    "trsfPasswd": "string",
    "occurAmt": "int64",
}
__OES_ISSUE_BASE_INFO_PKT = {
    "securityId": "string",
    "mktId": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "productType": "uint8",
    "issueType": "uint8",
    "isCancelAble": "uint8",
    "isReApplyAble": "uint8",
    "suspFlag": "uint8",
    "securityAttribute": "uint32",
    "isRegistration": "uint8",
    "isNoProfit": "uint8",
    "isWeightedVotingRights": "uint8",
    "isVie": "uint8",
    "__ISSUE_BASE_filler": "uint8",
    "startDate": "int32",
    "endDate": "int32",
    "issuePrice": "int32",
    "upperLimitPrice": "int32",
    "ceilPrice": "int32",
    "lowerLimitPrice": "int32",
    "floorPrice": "int32",
    "ordMaxQty": "int32",
    "ordMinQty": "int32",
    "qtyUnit": "int32",
    "issueQty": "int64",
    "alotRecordDay": "int32",
    "alotExRightsDay": "int32",
    "underlyingSecurityId": "string",
    "securityName": "string",
    "__ISSUE_BASE_reserve1": "string",
    "__ISSUE_BASE_reserve2": "string",
}
__OES_STOCK_BASE_INFO_PKT = {
    "securityId": "string",
    "mktId": "uint8",
    "productType": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "securityLevel": "uint8",
    "securityRiskLevel": "uint8",
    "currType": "uint8",
    "qualificationClass": "uint8",
    "securityStatus": "uint32",
    "securityAttribute": "uint32",
    "suspFlag": "uint8",
    "temporarySuspFlag": "uint8",
    "isDayTrading": "uint8",
    "isRegistration": "uint8",
    "isCrdCollateral": "uint8",
    "isCrdMarginTradeUnderlying": "uint8",
    "isCrdShortSellUnderlying": "uint8",
    "isNoProfit": "uint8",
    "isWeightedVotingRights": "uint8",
    "isVie": "uint8",
    "__STOCK_BASE_filler": "uint8",
    "priceLimit": "OesPriceLimitT",
    "priceTick": "int32",
    "priceUnit": "int32",
    "prevClose": "int32",
    "lmtBuyMaxQty": "int32",
    "buyOrdMaxQty": "int32",
    "lmtBuyMinQty": "int32",
    "buyOrdMinQty": "int32",
    "lmtBuyQtyUnit": "int32",
    "buyQtyUnit": "int32",
    "mktBuyMaxQty": "int32",
    "mktBuyMinQty": "int32",
    "mktBuyQtyUnit": "int32",
    "lmtSellMaxQty": "int32",
    "sellOrdMaxQty": "int32",
    "lmtSellMinQty": "int32",
    "sellOrdMinQty": "int32",
    "lmtSellQtyUnit": "int32",
    "sellQtyUnit": "int32",
    "mktSellMaxQty": "int32",
    "mktSellMinQty": "int32",
    "mktSellQtyUnit": "int32",
    "bondInterest": "int64",
    "parValue": "int64",
    "parPrice": "int64",
    "repoExpirationDays": "int32",
    "cashHoldDays": "int32",
    "auctionLimitType": "uint8",
    "auctionReferPriceType": "uint8",
    "__STOCK_BASE_filler1": "uint8",
    "auctionUpDownRange": "int32",
    "listDate": "int32",
    "maturityDate": "int32",
    "outstandingShare": "int64",
    "publicFloatShare": "int64",
    "underlyingSecurityId": "string",
    "fundId": "string",
    "securityName": "string",
    "__STOCK_BASE_reserve1": "string",
    "__STOCK_BASE_reserve2": "string",
}
__OES_ETF_BASE_INFO_PKT = {
    "fundId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "isPublishIOPV": "uint8",
    "isCreationAble": "uint8",
    "isRedemptionAble": "uint8",
    "isDisabled": "uint8",
    "__ETF_BASE_filler": "uint8",
    "componentCnt": "int32",
    "creRdmUnit": "int32",
    "maxCashRatio": "int32",
    "nav": "int32",
    "navPerCU": "int64",
    "dividendPerCU": "int64",
    "tradingDay": "int32",
    "preTradingDay": "int32",
    "estiCashCmpoent": "int64",
    "cashCmpoent": "int64",
    "creationLimit": "int64",
    "redemLimit": "int64",
    "netCreationLimit": "int64",
    "netRedemLimit": "int64",
}
__OES_ETF_COMPONENT_BASE_INFO_PKT = {
    "fundId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "fundMktId": "uint8",
    "subFlag": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "isTrdComponent": "uint8",
    "__ETF_COMPONENT_BASE_filler": "uint8",
    "prevClose": "int32",
    "qty": "int32",
    "premiumRatio": "int32",
    "premiumRate": "int32",
    "discountRatio": "int32",
    "creationSubCash": "int64",
    "redemptionSubCash": "int64",
    "redemptionCashSub": "int64",
}
__OES_CASH_ASSET_BASE_INFO_PKT = {
    "cashAcctId": "string",
    "custId": "string",
    "currType": "uint8",
    "cashType": "uint8",
    "cashAcctStatus": "uint8",
    "isFundTrsfDisabled": "uint8",
    "__CASH_ASSET_BASE_filler": "uint8",
    "beginningBal": "int64",
    "beginningAvailableBal": "int64",
    "beginningDrawableBal": "int64",
    "disableBal": "int64",
    "reversalAmt": "int64",
    "manualFrzAmt": "int64",
    "totalDepositAmt": "int64",
    "totalWithdrawAmt": "int64",
    "withdrawFrzAmt": "int64",
    "totalSellAmt": "int64",
    "totalBuyAmt": "int64",
    "buyFrzAmt": "int64",
    "totalFeeAmt": "int64",
    "feeFrzAmt": "int64",
    "marginAmt": "int64",
    "marginFrzAmt": "int64",
}
__OES_CUST_BASE_INFO_PKT = {
    "custId": "string",
    "custType": "uint8",
    "status": "uint8",
    "riskLevel": "uint8",
    "originRiskLevel": "uint8",
    "institutionFlag": "uint8",
    "investorClass": "uint8",
    "__CUST_BASE_filler1": "uint8",
    "branchId": "int32",
    "__CUST_BASE_filler2": "uint32",
}
__OES_INV_ACCT_BASE_INFO_PKT = {
    "invAcctId": "string",
    "mktId": "uint8",
    "acctType": "uint8",
    "status": "uint8",
    "ownerType": "uint8",
    "optInvLevel": "uint8",
    "isTradeDisabled": "uint8",
    "__INV_ACCT_BASE_filler": "uint8",
    "limits": "uint64",
    "permissions": "uint64",
    "pbuId": "int32",
    "stkPositionLimitRatio": "int32",
    "subscriptionQuota": "int32",
    "kcSubscriptionQuota": "int32",
    "__INV_ACCT_BASE_reserve": "string",
}
__OES_STK_HOLDING_BASE_INFO_PKT = {
    "invAcctId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "productType": "uint8",
    "__HOLD_BASE_filler": "uint8",
    "originalHld": "int64",
    "originalCostAmt": "int64",
    "totalBuyHld": "int64",
    "totalSellHld": "int64",
    "sellFrzHld": "int64",
    "manualFrzHld": "int64",
    "totalBuyAmt": "int64",
    "totalSellAmt": "int64",
    "totalBuyFee": "int64",
    "totalSellFee": "int64",
    "totalTrsfInHld": "int64",
    "totalTrsfOutHld": "int64",
    "trsfOutFrzHld": "int64",
    "originalLockHld": "int64",
    "totalLockHld": "int64",
    "totalUnlockHld": "int64",
    "originalAvlHld": "int64",
    "maxReduceQuota": "int64",
}
__OES_ORD_REQ_LATENCY_FIELDS = __OES_ORD_REQ_LATENCY_FIELDS_IMPL
__OES_ORD_CNFM_LATENCY_FIELDS = __OES_ORD_CNFM_LATENCY_FIELDS_IMPL
__OES_TRD_CNFM_LATENCY_FIELDS = __OES_TRD_BASE_LATENCY_FIELDS
